name: ðŸš€ Auto-Deploy to Hostinger
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v4
      
      - name: ðŸ”¨ Build Website
        run: |
          npm install
          npm run build
      
      - name: ðŸ“‚ Sync to Hostinger
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 21
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          localDir: './dist/public/'
          remoteDir: './'
          options: '--verbose'
